### ISSUE TITLE
Outdated Polymer

### ISSUE THREAD

**Issue by shawnnosaurus** [LRNWebComponents/wysiwyg-hax#1]
Has this project stalled?

Polymer 3 and their new PWA project would be an amazing basis for a wysiwyg, especially if you have a design that will work as a mobile first approach.

**Comment by btopro** [comment]
Err no we work on it daily. This implements as a wrapper for hax-body. Work to automate the polymer 3 version is contingent upon https://GitHub.com/elmsln/wcfactory and it will help us Port all of our elements.


And I agree that this will be a killer wysiwyg for PWAs

**Comment by shawnnosaurus** [comment]
Apologies, I saw that only after this.

**Comment by btopro** [comment]
Np. Please feel free to jump in on hax-body or wcfactory queues. Thx for the question
